Update cmp highlighting example
zbirenbaum/copilot-cmp pull request #17
Opened 2022-08-09 03:10 UTC by sitiom

It is more extensible to lspkind's `symbol_map` to add the icon and add the proper kind name for `vim_item`.

2022-08-10 19:55 UTC, zbirenbaum commented
Most of the code in this PR (the entire `before` section) is actually unnecessary now since my upstream PR hrsh7th/nvim-cmp#1003 was merged about two weeks ago. This PR would have been great prior to that, but unfortunately I just forgot to update the docs and stuff here after it was merged which is entirely my bad and I apologize. Now, all that is necessary to do is add `Copilot` to the symbol map (as you did here) but none of the other vim_item stuff matters.

I just updated the docs, but intentionally only included an example of adding Copilot during the lspkind setup, rather than in the formatting as you did here. If you would like to rebase and update the PR to include the example of adding to the symbol map during formatting (just remove the before section), I'll merge it.

2022-08-11 01:53 UTC, sitiom commented
Done 🙂

2022-08-11 02:34 UTC, zbirenbaum requested changes
Ah, sorry I think the way I worded things was confusing. I didn't mean to replace what I had (as it is perfectly valid to add Copilot within the lspkind setup directly, I meant to add your example for cmp like so:

Example:
```lua
-- lspkind.lua
local lspkind = require("lspkind")
lspkind.init({
  symbol_map = {
    Copilot = "[]",
  },
},
```
Alternatively, you can add Copilot to the lspkind `symbol_map` within the cmp format function.
Example:
```lua
-- cmp.lua
cmp.setup {
  ...
  formatting = {
    format = lspkind.cmp_format({
      mode = "symbol",
      max_width = 50,
      symbol_map = { Copilot = "" }
    })
  }
  ...
}

2022-08-11 02:39 UTC, zbirenbaum commented
Also please combine into one commit either by git reset --soft HEAD~1 (or HEAD~2 if you commit the request changes as well) && git commit --amend or by rebasing

2022-08-11 02:58 UTC, sitiom commented
> Also please combine into one commit either by git reset --soft HEAD~1 (or HEAD~2 if you commit the request changes as well) && git commit --amend or by rebasing

Done. Can't you just use the squash function when you merge it from here?

2022-08-11 03:00 UTC, merged

2022-08-11 03:00 UTC, zbirenbaum commented
> > Also please combine into one commit either by git reset --soft HEAD~1 (or HEAD~2 if you commit the request changes as well) && git commit --amend or by rebasing
> 
> Done. Can't you just use the squash function when you merge it from here?

You are correct, I completely forgot about that, sorry :(